# Generated by Django 3.1 on 2020-09-03 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_type', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('contact_info', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('qc_pattern', models.CharField(max_length=50)),
                ('qc_interval', models.IntegerField(max_length=50)),
                ('cali_interval', models.IntegerField(max_length=50)),
                ('pm_interval', models.IntegerField(max_length=50)),
                ('plan_update_interval', models.IntegerField(max_length=50)),
                ('discription', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='img')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
