# Generated by Django 3.1 on 2020-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='cali_interval',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='machines',
            name='plan_update_interval',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='machines',
            name='pm_interval',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='machines',
            name='qc_interval',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='machines',
            name='qc_pattern',
            field=models.DurationField(),
        ),
    ]
