# Generated by Django 3.1 on 2020-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20200904_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='start_op_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
