# Generated by Django 3.1 on 2020-09-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machines_start_op_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='cali_interval',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='plan_update_interval',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='pm_interval',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='qc_interval',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='qc_pattern',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='start_op_date',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='supplier',
        ),
        migrations.AddField(
            model_name='machines',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='machines',
            name='cali_plan_interval',
            field=models.IntegerField(choices=[(1, 'Day(s)'), (2, 'Week(s)'), (3, 'Month(s)'), (4, 'Year(s)')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='machines',
            name='cali_plan_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='Calibration or PM need is needed in every'),
        ),
        migrations.AddField(
            model_name='machines',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machines',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start operating date: (mm/dd/yyyy) e.g. 12/31/2020'),
        ),
        migrations.AddField(
            model_name='machines',
            name='op_duration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='operation plan will be made until: (mm/dd/yyyy) e.g. 12/31/2020'),
        ),
        migrations.AddField(
            model_name='machines',
            name='qc_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='QC is needed in every:'),
        ),
        migrations.AddField(
            model_name='machines',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='machines',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machines',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug (format is title-code e.g. pentra-01)'),
        ),
    ]
