# Generated by Django 3.1 on 2020-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20200907_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.TextField(null=True)),
                ('contact_phone', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
    ]
