# Generated by Django 3.1 on 2020-09-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_auto_20200912_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.suppliers'),
        ),
    ]
