# Generated by Django 3.1 on 2020-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_auto_20200914_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='document',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
