# Generated by Django 3.1 on 2020-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_machines_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='document',
            field=models.FileField(null=True, upload_to='media/suppliers/'),
        ),
        migrations.AlterField(
            model_name='machines',
            name='document',
            field=models.FileField(null=True, upload_to='media/machines/'),
        ),
    ]
