# Generated by Django 3.1 on 2020-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_auto_20200914_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='qc_plan_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='QC is needed in every'),
        ),
    ]
