# Generated by Django 3.1 on 2020-09-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0011_auto_20200914_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='slug',
        ),
    ]
