# Generated by Django 3.1 on 2020-09-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0012_remove_machines_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
