# Generated by Django 3.1 on 2020-10-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Procedure', 'Procedure'), ('Form', 'Form'), ('WI', 'WI'), ('Others', 'Others')], max_length=100, null=True)),
                ('department', models.CharField(blank=True, choices=[('DC', 'DC'), ('QMS', 'QMS'), ('AD', 'AD'), ('ML', 'ML')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rev', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True, verbose_name=' in mm/dd/yyyy format (e.g. 12/31/2020)')),
                ('indexing_method', models.CharField(blank=True, max_length=100, null=True)),
                ('related_procedure', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True)),
                ('retention_period', models.CharField(blank=True, max_length=100, null=True)),
                ('original_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('distributed_dept', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
