# Generated by Django 3.1 on 2020-10-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
