# Generated by Django 3.1 on 2020-10-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documents_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='external_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name=' in mm/dd/yyyy format (e.g. 12/31/2020)')),
                ('controlled_location', models.CharField(blank=True, choices=[('DC', 'DC'), ('QMS', 'QMS'), ('AD', 'AD'), ('ML', 'ML')], max_length=100, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
