# Generated by Django 3.1 on 2020-10-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_external_documents_current_ext_doc_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='external_documents',
            name='current_ext_doc_rev',
        ),
    ]
