# Generated by Django 3.1 on 2020-11-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_dar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dar',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Approved Person (Filled by DC)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc.Code (Filled by request person)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='dar_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Requested Person (Filled by DC)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='detail',
            field=models.CharField(blank=True, choices=[('Create New Document', 'Create New Document'), ('Update Revision', 'Update Revision')], max_length=200, null=True, verbose_name='Request Detail (Filled by request person)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc.Name (Filled by request person)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='purpose',
            field=models.CharField(blank=True, choices=[('DC', 'DC'), ('QMS', 'QMS'), ('AD', 'AD'), ('ML', 'ML')], max_length=100, null=True, verbose_name='Request Purpose (Filled by request person)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fill date in mm/dd/yyyy format (e.g. 12/31/2020)(Filled by request person)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remark (Filled by DC)'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Requested Person (Filled by request person)'),
        ),
    ]
